#!/bin/bash
# Summary: List all $LANGDOCK versions available to ${LANGDOCK}dock
# Usage: ${LANGDOCK}dock versions
#
# List all $LANGDOCK versions available to ${LANGDOCK}dock
#
# More information at https://github.com/lucasdc6/langdock#readme

set -e
[ -n "$LANGDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

touch $LANGDOCK_ROOT/etc/$LANGDOCK/repositories

# Provide langdock completions
if [ "$1" = "--complete" ]; then
  if [ "$#" -eq 1 ]; then
    echo --help
  fi
  exit 0
fi

LANGDOCK_IMAGES=( $(cat $LANGDOCKPATH/etc/$LANGDOCK/repositories) )

# Function to get installed versions
function show_versions {
  for IMAGE in "${LANGDOCK_IMAGES[@]}"
  do
    docker images | awk -v image=$IMAGE '($1 == image) {print $1":"$2;}'
  done | tee $LANGDOCKPATH/etc/$LANGDOCK/versions
}

VERSIONS=`show_versions`

if [ -z "$VERSIONS" ]; then
  cat <<HELP
No versions availables

Try with $LANGDOCK_COMMAND install <version>
HELP
else
  printf '%s\n' "${VERSIONS[@]}"
fi
