#!/usr/bin/env bash
# Summary: List all available ${LANGDOCK}dock commands
# Usage: ${LANGDOCK}dock commands [--sh|--no-sh]

set -e
[ -n "$LANGDOCK_DEBUG" ] && set -x

# Provide langdock completions
if [ "$1" = "--complete" ]; then
  if [ $# -eq 1 ]; then
    echo --sh
    echo --no-sh
    echo --help
  fi
  exit 0
fi

if [ "$1" = "--sh" ]; then
  sh=1
  shift
elif [ "$1" = "--no-sh" ]; then
  nosh=1
  shift
fi

IFS=: paths=($PATH $LANGDOCKPATH/plugins)

shopt -s nullglob

{ for path in "${paths[@]}"; do
    search=(${path}/langdock-* ${path}/$LANGDOCK_COMMAND/${LANGDOCK_COMMAND}-plugin-*)
    for command in ${search[*]}; do
      command="${command##*langdock-}"
      if [ -n "$sh" ]; then
        if [ "${command:0:3}" = "sh-" ]; then
          echo "${command##sh-}"
        fi
      elif [ -n "$nosh" ]; then
        if [ "${command:0:3}" != "sh-" ]; then
          echo "${command##sh-}"
        fi
      else
        command="${command##*${LANGDOCK_COMMAND}-plugin-}"
        echo "${command##sh-}"
      fi
    done
  done
} | sort | uniq
