#!//usr/bin/env bash
# Summary: Generate a command template
# Usage: ${LANGDOCK}dock generate-command [<command-name>]
# Generate a command for ${LANGDOCK} named by <command-name>
# <command-name> default value = "$LANGDOCK" 

LANGDOCK_COMMAND=${1:-$LANGDOCK}
LANGDOCK_COMMAND_UPPER=`echo $LANGDOCK_COMMAND | tr a-z A-Z`

cat > $LANGDOCKPATH/commands/$LANGDOCK_COMMAND <<COMMAND
#!//usr/bin/env bash

${LANGDOCK_COMMAND_UPPER}_CLI_DOCKER_IMAGE=\`${LANGDOCK}dock version-name\`

if [ "\$${LANGDOCK_COMMAND_UPPER}_CLI_DOCKER_IMAGE" = "system" -o \$? -eq 1 ]; then
  \$(whereis -b $LANGDOCK_COMMAND | awk '{print \$3}') \$@
  exit 0
fi

docker run --rm -it -u `id -u \$USER`:`id -g \$USER` -v "\$PWD:\$PWD" -w "\$PWD" \$${LANGDOCK_COMMAND_UPPER}_CLI_DOCKER_IMAGE \$@
COMMAND

chmod +x $LANGDOCKPATH/commands/$LANGDOCK_COMMAND

echo Command generated at $LANGDOCKPATH/commands/$LANGDOCK_COMMAND
