#!/usr/bin/env bash
# Summary: Configure the shell environment for langdock
# Usage: eval "$(langdock init - [<shell>])"

set -e
[ -n "$LANGDOCK_DEBUG" ] && set -x

# Provide langdock completions
if [ "$1" = "--complete" ]; then
  echo -
  echo bash
  echo fish
  echo ksh
  echo zsh
  echo --help
  exit
fi

print=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps -p "$PPID" -o 'args=' 2>/dev/null || true)"
  shell="${shell%% *}"
  shell="${shell##-}"
  shell="${shell:-$SHELL}"
  shell="${shell##*/}"
fi

root="${0%/*}/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    if [ -f "${HOME}/.bashrc" ] && [ ! -f "${HOME}/.bash_profile" ]; then
      profile='~/.bashrc'
    else
      profile='~/.bash_profile'
    fi
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load langdock automatically by appending"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and source (langdock init -|psub)'
      ;;
    * )
      echo 'eval "$(langdock init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${LANGDOCKPATH}/etc" "${LANGDOCKPATH}/commands"

case "$shell" in
fish )
  echo "set -gx PATH '${LANGDOCK_ROOT}/shims' \$PATH"
  echo "set -gx LANGDOCK_SHELL $shell"
;;
* )
  echo 'export PATH="'${LANGDOCK_ROOT}'/shims:${PATH}"'
  echo "export LANGDOCK_SHELL=$shell"
;;
esac

completion="${root}/completions/langdock.${shell}"
if [ -r "$completion" ]; then
  echo "source '$completion'"
fi

commands=(`langdock-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function langdock
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    source (langdock "sh-\$command" \$argv|psub)
  case '*'
    command langdock "\$command" \$argv
  end
end
EOS
  ;;
ksh )
  cat <<EOS
function langdock {
  typeset command
EOS
  ;;
* )
  cat <<EOS
langdock() {
  local command
EOS
  ;;
esac

if [ "$shell" != "fish" ]; then
IFS="|"
cat <<EOS
  command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\$(langdock "sh-\$command" "\$@")";;
  *)
    command langdock "\$command" "\$@";;
  esac
}
EOS
fi
