#!//usr/bin/env bash
# Summary: Uninstall a specific $LANGDOCK version
# Usage: ${LANGDOCK}dock uninstall
#
#  -f  Attempt to remove the specified version without prompting
#      for confirmation. If the version does not exist, do not
#      display an error message.
#
# See `${LANGDOCK}dock versions` for a complete list of installed versions.
#
# More information at https://github.com/lucasdc6/langdock#readme

set -e
[ -n "$LANGDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

# Provide langdock completions
if [ "$1" = "--complete" ]; then
  if echo $@ ; then
    cat $LANGDOCKPATH/etc/$LANGDOCK/versions
  fi
  echo --force
  echo --help
  exit 0
fi

[ "$#" -eq 0 ] && langdock-help $COMMAND && exit

# Function to uninstall a langdock version
# Arguments
#   1: version
function uninstall_langdock_version {
  docker image rm $1 -f
  echo -e "\n$1 removed\n"
  VERSIONS=( `langdock-versions` )
  ACTUAL_VERSION=`langdock-global || true`
  [ "$ACTUAL_VERSION" = "$1" ] && langdock-global ${VERSIONS[0]}
  exit 0
}

# Function to generate versions list from repositories
# Arguments
#   1: array of elements
function createmenu {
  echo "Select a version to uninstall"
  select option; do # in "$@" is the default
    if [ "$REPLY" -eq $# ];
    then
      echo "Exiting..."
      break;
    elif [ 1 -le "$REPLY" ] && [ "$REPLY" -le $(($#-1)) ];
    then
      echo "You selected $option which is option $REPLY"
      [ "$OPTIONS" = "-f"  ] && ( echo "Removing docker image.."; uninstall_langdock_version $option; )
      echo "Are you shure?"
      select response in yes no; do
        if [ "$response" = "yes" ]; then
          echo "Removing docker image.."
          uninstall_langdock_version $option
        elif [ "$response" = "no" ]; then
          echo "Exiting..."
        fi
        break;
      done
      break;
    else
      echo "Incorrect Input: Select a number 1-$#"
    fi
  done
}

# Config getopt
TEMP=`getopt -o f --long force -n $PROG -- "$@"`
eval set -- "$TEMP"

# Parse arguments
while true ; do
  case "$1" in
    -f|--force)
      OPTIONS="-f"
      shift;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

[ "$OPTIONS" = "-f" ] && uninstall_langdock_version $1 && exit 0

VERSION=(`langdock versions | grep "$1" || true`)

[ ${#VERSION[@]} -eq 0 ] && ( echo "${LANGDOCK}dock: version \`$1' not installed"; exit 1 )

VERSION=(${VERSION[@]} "exit")
createmenu ${VERSION[@]}
