#!//usr/bin/env bash
# Summary: Show the current $LANGDOCK version and its origin
# Usage: ${LANGDOCK}dock version
#
# Shows the currently selected $LANGDOCK version and how it was
# selected.
# To obtain only the version string, use `${LANGDOCK}dock version-name'.
# To obtaing only the path to origin file who set the version, use
# `${LANGDOCK}dock version-origin'.
#
# More information at https://github.com/lucasdc6/langdock#readme

set -e
[ -n "$LANGDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

# Provide langdock completions
if [ "$1" = "--complete" ]; then
  if [ "$#" -eq 1 ]; then
    echo --help
  fi
  exit 0
fi

function upsearch {
  slashes=${PWD//[^\/]/}
  directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -e "$directory/$1" && echo "$directory/$1" && return
    directory="$directory/.."
  done
}

if langdock local $PARAMS > /dev/null; then
  LANGDOCKVERSION=`upsearch ".$LANGDOCK-version"`
  echo "`langdock-local $PARAM` (set by `realpath $LANGDOCKVERSION`)"
elif langdock global $PARAM > /dev/null; then
  echo "`langdock-global $PARAM` (set by $LANGDOCKPATH/etc/$LANGDOCK/version)"
else
  echo "No $LANGDOCK version setted"
  exit 1
fi
