#!//usr/bin/env bash

set -e

export LANGDOCK=${LANGDOCK:-lang}
export LANGDOCK_COMMAND=${LANGDOCK}dock

if [ "$1" = "--debug" ]; then
  export LANGDOCK_DEBUG=true
  shift
fi

if [ -n "$LANGDOCK_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

# Get the basename and main path of script
export PROG=`basename $0`

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "${LANGDOCK}dock $*"
    fi
  } >&2
  exit 1
}

[ -z "$LANGDOCK_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"

READLINK=$(type -p greadlink readlink | head -1)
[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${LANGDOCK_ROOT}" ]; then
  LANGDOCK_ROOT="${HOME}/.langdock"
else
  LANGDOCK_ROOT="${LANGDOCK_ROOT%/}"
fi
export LANGDOCK_ROOT

LANGDOCKPATH=${LANGDOCKPATH:-$LANGDOCK_ROOT}

if [ -z "${LANGDOCK_DIR}" ]; then
  LANGDOCK_DIR="$PWD"
else
  [[ $LANGDOCK_DIR == /* ]] || LANGDOCK_DIR="$PWD/$LANGDOCK_DIR"
  cd "$LANGDOCK_DIR" 2>/dev/null || abort "cannot change working directory to \ `$LANGDOCK_DIR`"
  LANGDOCK_DIR="$PWD"
  cd $OLDPWD
fi
export LANGDOCK_DIR

shopt -s nullglob

export PATH="$LANGDOCKPATH/libexec:$LANGDOCKPATH/plugins/$LANGDOCK_COMMAND:${PATH}"

command="$1"
case "$command" in
  "" )
    { langdock-help
    } | abort
    ;;
  -v | --version )
    cat $LANGDOCKPATH/VERSION
    echo
    ;;
  -h | --help )
    exec langdock-help
    ;;
  * )
    command_path="$(command -v "langdock-$command" || command -v "${LANGDOCK_COMMAND}-plugin-$command" || true)"
    [ -n "$command_path" ] || abort "no such command \`$command'"

    shift 1
    if [ "$1" = --help ]; then
      if [[ "$command" == "sh-"* ]]; then
        echo "langdock help \"$command\""
      else
        exec langdock-help "$command"
      fi
    else
      exec "$command_path" "$@"
    fi
    ;;
esac
